name: .NET CI - NUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup .NET SDK (adjust version to your project)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3. Run NUnit tests
      - name: Run NUnit tests
        run: dotnet test ./MyApp.Tests/MyApp.Tests.csproj
