name: .NET CI - NUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup .NET SDK (adjust version to your project)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      
      - name: List repo files
        run: ls -R

      # 3. Run NUnit tests
      - name: Restore dependencies
        run: dotnet restore MyApp.Tests/MyApp.Tests.sln

      - name: Build solution
        run: dotnet build MyApp.Tests/MyApp.Tests.sln --configuration Release --no-restore

      - name: Run NUnit tests
        run: dotnet test MyApp.Tests/MyApp.Tests.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
